substitutions:
  node_name: basement-btproxy
  display_name: Basement Bluetooth Proxy

packages:
  esp32dev: !include common/esp32dev.yaml
  bluetooth_proxy: !include common/bluetooth_proxy.yaml
  web_server: !include common/web_server.yaml
