substitutions:
  node_name: basement-btproxy
  display_name: Basement Bluetooth Proxy

packages:
  esp32_c3_devkit_m1: !include common/esp32_c3_devkit_m1.yaml
  bluetooth_proxy: !include common/bluetooth_proxy.yaml
  web_server: !include common/web_server.yaml
