substitutions:
  node_name: clock
  display_name: Clock

packages:
  esp32_c3_devkit_m1: !include common/esp32_c3_devkit_m1.yaml
  web_server: !include common/web_server.yaml

esphome:
  name_add_mac_suffix: true

i2c:
  sda: GPIO6
  scl: GPIO5
  frequency: 300kHz    
  scan: true

font:
  - file: "fonts/7segment.ttf"
    id: segment_font
    size: 60

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Detroit
    servers:
     - 10.73.95.249
     - 0.pool.ntp.org

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    lambda: |-
      auto time = id(sntp_time).now();
      it.strftime(2, 0, id(segment_font), "%I:%M", time);
