substitutions:
  node_name: "ezsalt"
  display_name: "EZSalt"

packages:
  device_base: !include common/device_base.yaml
  web_server: !include common/web_server.yaml

esp8266:
  board: d1_mini

i2c:
  sda: D6
  scl: D7
  scan: True

sensor:
  - platform: vl53l0x
    name: softener1_salt_level
    update_interval: 60s
    address: 0x29
    unit_of_measurement: "Inches"
    device_class: "distance"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 39.37  # convert from mm to inches
      - offset: -35      # height of salt container
      - multiply: -1     # back to a positive value
      - median:
          window_size: 7
          send_every: 4
          send_first_at: 3        
