substitutions:
  node_name: garage-zwave
  display_name: Garage ZWave

packages:
  esp32s3-wroom1: !include common/esp32-s3-wroom-1.yaml
  bluetooth_proxy: !include common/bluetooth_proxy.yaml
  web_server: !include common/web_server.yaml
  usb_cdc: !include common/usb-cdc.yaml
  wifi: !include common/wifi.yaml

