substitutions:
  node_name: "hot-water-heater"
  display_name: "Hot Water Heater"

packages:
  device_base: !include common/device_base.yaml
  web_server: !include common/web_server.yaml
  power_meter: !include
    file: common/glow.yaml
    vars:
      sensor_name: "DHW"
      sensor_id: "dhw"
      pin_number: GPIO7
      pin_pullup: true
      pin_inverted: true
      pulses_per_kwh: "800"

wifi:
  manual_ip:
    static_ip: 10.73.95.44
    gateway: 10.73.95.1
    subnet: 255.255.255.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

dallas:
  - pin: GPIO3
    update_interval: 10s

sensor:
  - platform: dallas
    index: 0
    name: "Recirculation Return Temp"
    id: recirculation_return_temp
    filters:
      - filter_out: NAN

switch:
  - platform: gpio
    id: pump_power
    pin: 10

climate:
  - platform: thermostat
    name: "Pump Thermostat"
    id: pump_thermostat
    sensor: recirculation_return_temp
    heat_action:
      - switch.turn_on: pump_power
    idle_action:
      - switch.turn_off: pump_power
    heat_deadband: 5 °C
    min_idle_time: 5s
    min_heating_run_time: 5s
    min_heating_off_time: 5s
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 38 °C
      - name: Away
        default_target_temperature_low: 0 °C
