substitutions:
  node_name: "hot-water-heater"
  display_name: "Hot Water Heater"

packages:
  device_base: !include common/device_base.yaml
  web_server: !include common/web_server.yaml
  power_meter: !include
    file: common/glow.yaml
    vars:
      sensor_name: "DHW"
      sensor_id: "dhw"
      pin_number: GPIO8
      pin_pullup: true
      pin_inverted: true
      pulses_per_kwh: "800"

wifi:
  manual_ip:
    static_ip: 10.73.95.44
    gateway: 10.73.95.1
    subnet: 255.255.255.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

dallas:
  - pin: GPIO3
    update_interval: 10s

sensor:
  - platform: dallas
    index: 0
    name: "Recirculation Return Temp"
    id: recirculation_return_temp
    filters:
      - filter_out: NAN

switch:
  - platform: gpio
    id: pump_power
    name: "Pump Power"
    pin: 10

climate:
  - platform: bang_bang
    name: "Pump Thermostat"
    id: pump_thermostat
    sensor: recirculation_return_temp
    heat_action:
      - switch.turn_on: pump_power
    idle_action:
      - switch.turn_off: pump_power
    visual:
      max_temperature: 50
      min_temperature: 0
    default_target_temperature_low: 28
    default_target_temperature_high: 38

text_sensor:
  - platform: homeassistant
    name: "House Mode"
    entity_id: input_select.house_mode
    id: house_mode
    on_value:
      - if:
          condition:
            text_sensor.state:
              id: house_mode
              state: "Home"
          then:
            - climate.control:
                id: pump_thermostat
                mode: HEAT
          else:
            - climate.control:
                id: pump_thermostat
                mode: "OFF"
