substitutions:
  node_name: basement-btproxy
  display_name: Basement Bluetooth Proxy

packages:
  esp32_c3_devkit_m1: !include common/esp32_c3_devkit_m1.yaml
  web_server: !include common/web_server.yaml

esphome:
  libraries:
    - hopperpop/Sgp4
    - davidarmstrong/WMM_Tinier

globals:
  - id: tle_str
    type: std::string
    restore_value: yes
    max_restore_data_length: 200
    initial_value: ""

  - id: latitude
    type: double
    initial_value: "42.331095157801485"

  - id: longitude
    type: double
    initial_value: "-83.87847751379014"

  - id: altitude
    type: int
    initial_value: "285"

i2c:
  sda: GPIO21
  scl: GPIO20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"

stepper:
  - platform: uln2003
    id: azimuth_stepper
    pin_a: GPIO7
    pin_b: GPIO6
    pin_c: GPIO5
    pin_d: GPIO4
    max_speed: 250 steps/s

servo:
  - id: elevation_servo
    output: elevation_pwm

output:
  - platform: ledc
    pin: GPIO0
    id: elevation_pwm

# https://celestrak.org/NORAD/elements/gp.php?CATNR=25544&FORMAT=tle
# once a day pull the ISS TLE from ^that URL

# on_boot:
#   - init sat tracker
#   - init compass, find true north
#   - do once-daily init

# https://github.com/Hopperpop/Sgp4-Library/blob/master/examples/Sgp4Tracker/Sgp4Tracker.ino

# on_loop:
#   - sat.findsat(current time)
#   - update azimuth, elevation, distance, lat, lon, alt, visibility
#   - update display
#   - update servo and stepper
