substitutions:
  node_name: kitchen-door-light
  display_name: Kitchen Slider Door Light

packages:
  esp32_c3_devkit_m1: !include common/esp32_c3_devkit_m1.yaml
  bluetooth_proxy: !include common/bluetooth_proxy.yaml
  web_server: !include common/web_server.yaml  
  wifi: !include common/wifi.yaml

logger:
  level: DEBUG

wifi:
  manual_ip:
    static_ip: 10.73.95.180
    gateway: 10.73.95.1
    subnet: 255.255.255.0

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RBG
    is_rgbw: true
    chipset: SK6812
    num_leds: 11
    pin: 8
    internal: true
    id: light_int

  - platform: partition
    name: "Light One"
    segments:
      - id: light_int
        from: 1
        to: 10
    restore_mode: RESTORE_AND_OFF    
