substitutions:
  node_name: kitchen-door-light
  display_name: Kitchen Slider Door Light

packages:
  esp32_c3_devkit_m1: !include common/esp32_c3_devkit_m1.yaml
  web_server: !include common/web_server.yaml  
  wifi: !include common/wifi.yaml

esp32:
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  manual_ip:
    static_ip: 10.73.95.180
    gateway: 10.73.95.1
    subnet: 255.255.255.0

light:
  - platform: neopixelbus
    type: RBWG
    variant: SK6812
    num_leds: 11
    pin: 8
    internal: true
    id: light_int

  - platform: partition
    name: "Full Bar"
    segments:
      - id: light_int
        from: 1
        to: 10
    restore_mode: RESTORE_AND_OFF

  - platform: partition
    name: "Top Half"
    segments:
      - id: light_int
        from: 1
        to: 6
    restore_mode: RESTORE_AND_OFF

  - platform: partition
    name: "Bottom Half"
    segments:
      - id: light_int
        from: 6
        to: 10
    restore_mode: RESTORE_AND_OFF            
