substitutions:
  node_name: "holiday-lights-2"
  display_name: "Holiday Lights 2"

packages:
  esp8266: !include common/esp8266.yaml
  web_server: !include common/web_server.yaml

logger:
  level: DEBUG

switch:
  - platform: gpio
    pin: GPIO5
    id: relay
    internal: true

wled:

light:
  - platform: neopixelbus
    type: WRGB
    variant: SK6812
    num_leds: 60
    pin: GPIO1
    name: "Light One"
    id: light_one
    internal: true

  - platform: neopixelbus
    type: WRGB
    variant: SK6812
    num_leds: 60
    pin: GPIO2
    name: "Light Two"
    id: light_two
    internal: true

  - platform: partition
    name: "Front Lights"
    restore_mode: RESTORE_DEFAULT_OFF
    segments:
      - id: light_two
        from: 0
        to: 59
        reversed: true
      - id: light_one
        from: 0
        to: 59

    on_turn_on:
      - switch.turn_on: relay

    on_turn_off:
      - switch.turn_off: relay

    effects:
      - addressable_rainbow:
          name: Rainbow
          width: 80
          speed: 5
      - addressable_twinkle:
          name: Twinkle
          twinkle_probability: 50%
      - addressable_lambda:
          name: Halloween
          lambda: |-
            Color colors[3] = {
              // r    g    b    w
              {255, 165,   0,   0}, // orange
              {148,   0, 211,   0}, // purple
              {  0, 255,   0,   0}, // green
            };

            for (int i = it.size() - 1; i > 0; i--) {
              it[i] = colors[i % 3];
            }
      - addressable_lambda:
          name: Christmas
          lambda: |-
            Color colors[3] = {
              // r    g    b    w
              {255,   0,   0,   0}, // red
              {  0, 255,   0,   0}, // green
              {  0,   0,   0, 255}, // white
            };

            for (int i = it.size() - 1; i > 0; i--) {
              it[i] = colors[i % 3];
            }
      - wled:
