substitutions:
  node_name: "m5-echo-2"
  display_name: "Echo 2"

packages:
  m5_echo: !include common/m5-echo.yaml
  wifi: !include common/wifi.yaml

light:
  - platform: esp32_rmt_led_strip
    id: light_2
    name: LED 2
    pin: GPIO21
    default_transition_length: 0s
    chipset: SK6812
    num_leds: 5
    rgb_order: GRB
    is_rgbw: true
    rmt_channel: 1
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%
  
