#[10:35:12][D][text_sensor:064]: 'BLE Devices Scanner': Sending state '{"timestamp":1721658912,"address":"50:54:7B:80:D3:78","rssi":-36,"name":"Battery Monitor"}'

substitutions:
  node_name: "red-battery-monitor"
  display_name: "Red Battery Monitor"

packages:
  device_base: !include common/device_base.yaml
  web_server: !include common/web_server.yaml
  bluetooth_proxy: !include common/bluetooth_proxy.yaml
  wifi: !include common/wifi.yaml

esp32:
  board: nodemcu-32s  
  
logger:
  level: DEBUG

