substitutions:
  node_name: shed-zwave
  display_name: Shed ZWave

packages:
  esp32s3-wroom1: !include common/esp32-s3-wroom-1.yaml
  bluetooth_proxy: !include common/bluetooth_proxy.yaml
  web_server: !include common/web_server.yaml
  usb_cdc: !include common/usb-cdc.yaml

ethernet:
  type: W5500
  clk_pin: GPIO13
  mosi_pin: GPIO11
  miso_pin: GPIO12
  cs_pin: GPIO14
  interrupt_pin: GPIO10
  reset_pin: GPIO09
