esphome:
  name: ${node_name}
  friendly_name: ${display_name}
  name_add_mac_suffix: false

api:
  encryption:
    key: !secret home_assistant_encryption_key

wifi:
  id: wifi_id
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

ota:
  - platform: esphome
    password: !secret ota_password

switch:
  - platform: safe_mode
    name: "Flash Mode (Safe Mode)"
    icon: "mdi:cellphone-arrow-down"

button:
  - platform: restart
    id: button_restart
    name: "Restart"
    disabled_by_default: true

binary_sensor:
  - platform: status
    name: "${display_name} Status"

sensor:
  - platform: uptime
    id: uptime_sensor
    name: "Uptime Sensor"
    update_interval: 1min

  - platform: wifi_signal
    id: wifi_strength
    name: "Wifi Strength"
    update_interval: 1min

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "America/Detroit"
