sensor:
  - platform: pulse_meter
    name: '${sensor_name} Power Consumption'
    id: ${sensor_id}_energy_pulse_meter
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin:
      number: ${pin_number}
      inverted: true
      mode:
        input: true
        pullup: true
    
    internal_filter: 100ms
    timeout: 30s
  
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / 800) * 1000.0);
    total:
      name: '${sensor_name} Total Energy'
      id: ${sensor_id}_total_energy
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / 800);

  # Total day useage
  - platform: total_daily_energy
    name: '${sensor_name} Daily Energy'
    id: ${sensor_id}_total_daily_energy
    power_id: ${sensor_id}_energy_pulse_meter
    unit_of_measurement: 'kWh'
    icon: mdi:circle-slice-3
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
