substitutions:
  pin_number: "1"
  pin_inverted: "true"
  pin_pullup: "true"
  pin_pulldown: "false"
  pulses_per_kwh: "1000"
  internal_filter: "10ms"

sensor:
  - platform: pulse_meter
    name: '${sensor_name} Power Consumption'
    id: ${sensor_id}_energy_pulse_meter
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin:
      number: ${pin_number}
      inverted: ${pin_inverted}
      mode:
        input: true
        pullup: ${pin_pullup}
        pulldown: ${pin_pulldown}
    
    internal_filter: ${internal_filter}
    internal_filter_mode: EDGE
    timeout: 30s
  
    filters:
      # multiply value = (60 / imp value) * 1000
      # - multiply: 60
      - lambda: return x * ((60.0 / ${pulses_per_kwh}) * 1000.0);
      - clamp:
          max_value: 48000.0
          ignore_out_of_range: true
    total:
      name: '${sensor_name} Total Energy'
      id: ${sensor_id}_total_energy
      unit_of_measurement: 'kWh'
      icon: mdi:circle-slice-3
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 3
      filters:
        # multiply value = 1 / imp value
        # - multiply: 0.001
        - lambda: return x * (1.0 / ${pulses_per_kwh});

  # Total day useage
  - platform: total_daily_energy
    name: '${sensor_name} Daily Energy'
    id: ${sensor_id}_total_daily_energy
    power_id: ${sensor_id}_energy_pulse_meter
    unit_of_measurement: 'kWh'
    icon: mdi:circle-slice-3
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
