packages:
  device_base: !include device_base.yaml
  web_server: !include web_server.yaml
  wifi: !include wifi.yaml

esp8266:
  board: nodemcuv2

uart:
  rx_pin: RX
  baud_rate: 4800
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status"

sensor:
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 2
      filters:
        - throttle_average: 10s

    voltage:
      name: "Voltage"
      accuracy_decimals: 2
      filters:
        - throttle_average: 10s

    power:
      name: "Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: 10s

    energy:
      name: "Energy"
      accuracy_decimals: 2
      filters:
        - throttle: 10s

  - platform: total_daily_energy #(Optional, not specific to cse7766)
    name: "Daily Energy"
    power_id: my_power
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

time:
  - platform: sntp #(required for total_daily_energy)
    id: my_time

status_led:
  pin:
    number: GPIO13
    inverted: True
